### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by alanluqman** [nedith/first-capstone-project#2]
## Highlights
Well Done Edith, you did great. Everything works correctly and smoothly 👍.

## Change suggestions :

1. In the home page both desktop and mobile menu, you don't need to have (Join) link! Because actually it's not exist on your website, I suggest you to change it to (featured Speakers).
2. In the About page, both Desktop and mobile menu do not need to have (Join, Program) links ! Because actually they are not exist in this page, I recommend you to change it.
3. When you click on links in menu, your page will jump to specific section immediately, So you had better to change scroll behavior to smooth.

**Comment by nedith** [comment]
Thank you for the feedback Alan :smiley: I have implemented the suggested changes and my page looks so much better :+1:
